"""
Shared schemas and helpers for models.
Purged of OpenRouter API connection logic.
"""

from typing import Any, Dict, List, Optional, Union
from enum import Enum
from pydantic import BaseModel, Field


def extract_text_content(content: Any) -> str:
    """Extract string content safely from str, list (e.g. thinking/vision blocks), or dict."""
    if content is None:
        return ""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for item in content:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict):
                if "text" in item and item["text"]:
                    parts.append(str(item["text"]))
                elif "thinking" in item and item["thinking"]:
                    parts.append(str(item["thinking"]))
                elif item.get("type") == "text" and "text" in item:
                    parts.append(str(item["text"]))
        return "\n".join(parts) if parts else str(content)
    if isinstance(content, dict):
        return content.get("text") or content.get("content") or str(content)
    return str(content)


class ModelType(Enum):
    """Available model types."""
    QWEN = "qwen"
    GEMINI_FLASH = "gemini_flash"
    MIMO = "mimo"
    DEEPSEEK = "deepseek"


class Message(BaseModel):
    """Chat message."""
    role: str = Field(..., description="Message role (system, user, assistant, tool)")
    content: Optional[Union[str, List[Any], Dict[str, Any]]] = Field(default=None, description="Message content")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(default=None, description="Tool calls generated by the model")
    tool_call_id: Optional[str] = Field(default=None, description="Tool call ID for tool responses")
    name: Optional[str] = Field(default=None, description="Name of the tool for tool responses")


class OpenRouterClient:
    """Dummy fallback class to satisfy legacy imports."""
    def __init__(self):
        pass