import asyncio
import json
import time
from typing import Dict, Any, Optional, List, AsyncGenerator, Union
from dataclasses import dataclass
from enum import Enum

import httpx
from pydantic import BaseModel, Field
import tiktoken

from src.utils.config import config


def extract_text_content(content: Any) -> str:
    """Extract string content safely from str, list (e.g. thinking/vision blocks), or dict."""
    if content is None:
        return ""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for item in content:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict):
                if "text" in item and item["text"]:
                    parts.append(str(item["text"]))
                elif "thinking" in item and item["thinking"]:
                    parts.append(str(item["thinking"]))
                elif item.get("type") == "text" and "text" in item:
                    parts.append(str(item["text"]))
        return "\n".join(parts) if parts else str(content)
    if isinstance(content, dict):
        return content.get("text") or content.get("content") or str(content)
    return str(content)


class ModelType(Enum):
    """Available model types."""
    QWEN = "qwen"
    GEMINI_FLASH = "gemini_flash"
    MIMO = "mimo"
    DEEPSEEK = "deepseek"


class Message(BaseModel):
    """Chat message."""
    role: str = Field(..., description="Message role (system, user, assistant, tool)")
    content: Optional[Union[str, List[Any], Dict[str, Any]]] = Field(default=None, description="Message content")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(default=None, description="Tool calls generated by the model")
    tool_call_id: Optional[str] = Field(default=None, description="Tool call ID for tool responses")
    name: Optional[str] = Field(default=None, description="Name of the tool for tool responses")


class ChatRequest(BaseModel):
    """Chat completion request."""
    model: str = Field(..., description="Model ID")
    messages: List[Message] = Field(..., description="Chat messages")
    temperature: float = Field(default=0.7, ge=0.0, le=2.0, description="Temperature")
    max_tokens: Optional[int] = Field(default=None, description="Maximum tokens to generate")
    stream: bool = Field(default=False, description="Whether to stream response")
    tools: Optional[List[Dict[str, Any]]] = Field(default=None, description="Available tools in OpenAI schema")
    tool_choice: Optional[str] = Field(default=None, description="Tool choice mode (e.g., 'auto')")
    provider: Optional[Dict[str, Any]] = Field(default=None, description="Provider-specific parameters")


class UsageDetails(BaseModel):
    """Usage details from OpenRouter."""
    prompt_tokens: int = Field(..., description="Prompt tokens")
    completion_tokens: int = Field(..., description="Completion tokens")
    total_tokens: int = Field(..., description="Total tokens")
    cost: float = Field(..., description="Cost in USD")
    is_byok: bool = Field(default=False, description="Is BYOK (Bring Your Own Key)")
    prompt_tokens_details: Optional[Dict[str, int]] = Field(default=None, description="Prompt token details")
    cost_details: Optional[Dict[str, float]] = Field(default=None, description="Cost details")
    completion_tokens_details: Optional[Dict[str, int]] = Field(default=None, description="Completion token details")


class ChatResponse(BaseModel):
    """Chat completion response."""
    id: Optional[str] = Field(default=None, description="Response ID")
    object: Optional[str] = Field(default=None, description="Object type")
    created: Optional[int] = Field(default=None, description="Creation timestamp")
    model: Optional[str] = Field(default=None, description="Model used")
    provider: Optional[str] = Field(default=None, description="Model provider")
    system_fingerprint: Optional[str] = Field(default=None, description="System fingerprint")
    choices: Optional[List[Dict[str, Any]]] = Field(default=None, description="Response choices")
    usage: Optional[UsageDetails] = Field(default=None, description="Token usage")
    error: Optional[Dict[str, Any]] = Field(default=None, description="Error returned by API")


@dataclass
class ModelCapabilities:
    """Model capabilities for routing decisions."""
    max_tokens: int
    supports_tools: bool
    supports_vision: bool
    reasoning_strength: float  # 0-1 scale
    coding_strength: float  # 0-1 scale
    speed: float  # 0-1 scale (higher = faster)
    cost_per_token: float  # USD per 1M tokens (average)


class OpenRouterClient:
    """Client for OpenRouter API."""
    
    def __init__(self):
        self.base_url = config.settings.openrouter_base_url
        self.api_key = config.settings.openrouter_api_key
        self.client = httpx.AsyncClient(
            timeout=config.settings.request_timeout,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
                "HTTP-Referer": "https://agenticai.local",  # Optional
                "X-Title": "AgenticAI",  # Optional
            }
        )
        
        # Model ID mapping — resolved from role assignments (Redis → SQLite → fallback).
        # These are used only by the legacy CLI path; the Tauri UI routes via IntelligentRouter.
        from src.controller.model_router import _resolve_role
        ms = getattr(self, 'memory_store', None)
        self.model_ids = {
            ModelType.QWEN:        _resolve_role('orchestrator', ms) or 'qwen/qwen3.7-flash',
            ModelType.GEMINI_FLASH: _resolve_role('multimodal', ms)  or 'google/gemini-2.5-flash-lite',
            ModelType.MIMO:        _resolve_role('reasoning', ms)    or 'deepseek/deepseek-v4-pro',
            ModelType.DEEPSEEK:    _resolve_role('coding', ms)       or 'deepseek/deepseek-v4-flash',
        }
        
        # Model capabilities (approximate, based on documentation)
        self.model_capabilities = {
            ModelType.QWEN: ModelCapabilities(
                max_tokens=32768,
                supports_tools=True,
                supports_vision=False,
                reasoning_strength=0.7,
                coding_strength=0.6,
                speed=0.8,
                cost_per_token=0.5,
            ),
            ModelType.GEMINI_FLASH: ModelCapabilities(
                max_tokens=8192,
                supports_tools=True,
                supports_vision=True,
                reasoning_strength=0.5,
                coding_strength=0.4,
                speed=0.9,
                cost_per_token=0.2,
            ),
            ModelType.MIMO: ModelCapabilities(
                max_tokens=32768,
                supports_tools=True,
                supports_vision=True,
                reasoning_strength=0.9,
                coding_strength=0.7,
                speed=0.6,
                cost_per_token=3.0,
            ),
            ModelType.DEEPSEEK: ModelCapabilities(
                max_tokens=128000,
                supports_tools=True,
                supports_vision=False,
                reasoning_strength=0.6,
                coding_strength=0.9,
                speed=0.7,
                cost_per_token=0.21,
            ),
        }
        
        # Tokenizer for approximate token counting
        try:
            self.tokenizer = tiktoken.get_encoding("cl100k_base")
        except:
            self.tokenizer = None
    
    async def chat_completion(
        self,
        messages: List[Message],
        model_type: Any,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        stream: bool = False,
        tools: Optional[List[Dict[str, Any]]] = None,
    ) -> ChatResponse:
        """Send chat completion request to OpenRouter."""
        if isinstance(model_type, ModelType):
            model_id = self.model_ids[model_type]
        else:
            raw_str = str(model_type).strip()
            known_providers = ["google", "gemini", "deepseek", "qwen", "anthropic", "claude", "openai", "groq", "mistral", "openrouter"]
            if ":" in raw_str:
                parts = raw_str.split(":", 1)
                prov = parts[0].lower().strip()
                if "/" not in parts[0] and prov in known_providers:
                    mid = parts[1]
                    if prov == "openrouter":
                        model_id = mid
                    elif prov in ["google", "gemini"]:
                        model_id = f"google/{mid}" if not mid.startswith("google/") else mid
                    elif prov == "deepseek":
                        model_id = f"deepseek/{mid}" if not mid.startswith("deepseek/") else mid
                    elif prov == "qwen":
                        model_id = f"qwen/{mid}" if not mid.startswith("qwen/") else mid
                    elif prov in ["anthropic", "claude"]:
                        model_id = f"anthropic/{mid}" if not mid.startswith("anthropic/") else mid
                    elif prov == "openai":
                        model_id = f"openai/{mid}" if not mid.startswith("openai/") else mid
                    elif prov in ["mistral"]:
                        model_id = f"mistralai/{mid}" if not mid.startswith("mistralai/") else mid
                    else:
                        model_id = mid
                else:
                    model_id = raw_str
            else:
                model_id = raw_str.replace("openrouter/", "")
                
            model_lower = model_id.lower()
            if "gemini" in model_lower and not model_lower.startswith("google/"):
                model_id = f"google/{model_id}"
            elif "deepseek" in model_lower and not model_lower.startswith("deepseek/"):
                model_id = f"deepseek/{model_id}"
            elif "qwen" in model_lower and not model_lower.startswith("qwen/"):
                model_id = f"qwen/{model_id}"
            elif "claude" in model_lower and not model_lower.startswith("anthropic/"):
                model_id = f"anthropic/{model_id}"
            elif ("mistral" in model_lower or "codestral" in model_lower) and not model_lower.startswith("mistralai/"):
                model_id = f"mistralai/{model_id}"
            
        # Use defaults if not provided
        if temperature is None:
            temperature = config.settings.temperature
        if max_tokens is None:
            caps = self.model_capabilities.get(model_type) if isinstance(model_type, ModelType) else None
            max_tokens = min(config.settings.max_tokens_per_request, caps.max_tokens if caps else 128000)
            
        provider = None
        if "deepseek" in model_id.lower():
            provider = {"parameters": {"reasoning_effort": "max"}}
        
        request = ChatRequest(
            model=model_id,
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens,
            stream=stream,
            tools=tools,
            tool_choice="auto" if tools else None,
            provider=provider,
        )
        
        max_retries = 2
        for attempt in range(max_retries + 1):
            try:
                from datetime import datetime
                current_time = datetime.now().strftime("%H:%M:%S")
                print(f"[{current_time}] 🤖 Requesting completion from model: {model_id} (Attempt {attempt+1}/{max_retries+1})...")
                response = await self.client.post(
                    f"{self.base_url}/chat/completions",
                    json=request.dict(exclude_none=True),
                )
                
                # Check for rate limiting
                if response.status_code == 429 and attempt < max_retries:
                    print(f"⚠️ Rate limited (429). Retrying in 2 seconds...")
                    await asyncio.sleep(2)
                    continue
                    
                response.raise_for_status()
                
                data = response.json()
                
                # Track cost
                if data.get("usage"):
                    usage = data["usage"]
                    input_tokens = usage.get("prompt_tokens", 0)
                    output_tokens = usage.get("completion_tokens", 0)
                    from datetime import datetime
                    current_time = datetime.now().strftime("%H:%M:%S")
                    print(f"[{current_time}] ✅ Response received from {model_id} (Tokens: {input_tokens} in, {output_tokens} out)")
                    config.track_cost(model_id, input_tokens, output_tokens)
                
                return ChatResponse(**data)
                
            except httpx.HTTPStatusError as e:
                print(f"HTTP error: {e.response.status_code} - {e.response.text}")
                if attempt == max_retries:
                    raise
            except Exception as e:
                print(f"Error in chat completion: {e}")
                if attempt == max_retries:
                    raise
    
    async def chat_completion_stream(
        self,
        messages: List[Message],
        model_type: ModelType,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> AsyncGenerator[str, None]:
        """Stream chat completion response."""
        model_id = self.model_ids[model_type]
        
        if temperature is None:
            temperature = config.settings.temperature
        if max_tokens is None:
            max_tokens = min(
                config.settings.max_tokens_per_request,
                self.model_capabilities[model_type].max_tokens
            )
            
        provider = None
        if "deepseek" in model_id.lower():
            provider = {"parameters": {"reasoning_effort": "max"}}
        
        request = ChatRequest(
            model=model_id,
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens,
            stream=True,
            provider=provider,
        )
        
        try:
            async with self.client.stream(
                "POST",
                f"{self.base_url}/chat/completions",
                json=request.dict(exclude_none=True),
                timeout=120.0,
            ) as response:
                response.raise_for_status()
                
                collected_content = []
                async for line in response.aiter_lines():
                    if line.startswith("data: "):
                        data = line[6:]
                        if data == "[DONE]":
                            break
                        
                        try:
                            chunk = json.loads(data)
                            if "choices" in chunk and chunk["choices"]:
                                delta = chunk["choices"][0].get("delta", {})
                                if "content" in delta and delta["content"]:
                                    content = delta["content"]
                                    collected_content.append(content)
                                    yield content
                        except json.JSONDecodeError:
                            continue
            
            # Track cost (approximate)
            if self.tokenizer and collected_content:
                full_response = "".join(collected_content)
                output_tokens = len(self.tokenizer.encode(full_response))
                # Estimate input tokens
                input_messages = "\n".join([m.content for m in messages])
                input_tokens = len(self.tokenizer.encode(input_messages))
                config.track_cost(model_id, input_tokens, output_tokens)
                
        except Exception as e:
            print(f"Error in streaming: {e}")
            raise
    
    def estimate_tokens(self, text: str) -> int:
        """Estimate token count for text."""
        if self.tokenizer:
            return len(self.tokenizer.encode(text))
        # Fallback: approximate 4 chars per token
        return len(text) // 4
    
    def get_model_capabilities(self, model_type: ModelType) -> ModelCapabilities:
        """Get capabilities for a model."""
        return self.model_capabilities[model_type]
    
    def get_available_models(self) -> List[Dict[str, Any]]:
        """Get list of available models with capabilities."""
        models = []
        for model_type, model_id in self.model_ids.items():
            caps = self.model_capabilities[model_type]
            models.append({
                "type": model_type.value,
                "id": model_id,
                "capabilities": {
                    "max_tokens": caps.max_tokens,
                    "supports_tools": caps.supports_tools,
                    "supports_vision": caps.supports_vision,
                    "reasoning_strength": caps.reasoning_strength,
                    "coding_strength": caps.coding_strength,
                    "speed": caps.speed,
                    "cost_per_token": caps.cost_per_token,
                }
            })
        return models
    
    async def close(self):
        """Close HTTP client."""
        await self.client.aclose()
    
    async def __aenter__(self):
        return self
    
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.close()
    
    async def summarize_content(
        self,
        content: str,
        max_tokens: int = 400,
        model_id: str = "openai/gpt-oss-120b",
    ) -> str:
        """Summarize content using gpt-oss-120b (free model)."""
        try:
            print(f"📝 Background Task: Summarizing chat history using {model_id}...")
            messages = [
                Message(role="system", content="You are a helpful assistant that creates concise summaries. Keep the summary under 400 tokens and preserve key information."),
                Message(role="user", content=f"Summarize the following content concisely:\n\n{content}"),
            ]
            
            from src.models.provider_router import ProviderRouter
            pr = ProviderRouter(self)
            dict_msgs = [{"role": m.role, "content": m.content} for m in messages]
            res = await pr.generate(dict_msgs, model_id=model_id, temperature=0.2, max_tokens=max_tokens)
            summary = res.get("content", "").strip() if isinstance(res, dict) else ""
            return summary if summary else self._fallback_summary(content, max_tokens)
            
        except Exception as e:
            print(f"Error in summarization: {e}")
            return self._fallback_summary(content, max_tokens)
    
    def _fallback_summary(self, content: str, max_tokens: int) -> str:
        """Fallback summary by truncation when API fails."""
        tokens = self.estimate_tokens(content)
        if tokens <= max_tokens:
            return content
        
        target_chars = max_tokens * 4
        if len(content) > target_chars:
            return content[:target_chars] + "..."
        return content

    async def extract_memory_facts(
        self,
        content: str,
        model_id: str = "openai/gpt-oss-120b",
    ) -> List[str]:
        """Extract factual memories from a chat conversation."""
        try:
            print(f"🧠 Background Task: Extracting enduring factual memories using {model_id}...")
            messages = [
                Message(
                    role="system",
                    content=(
                        "You are an expert AI Memory Curator.\n"
                        "Analyze the text and extract ONLY high-value, enduring personal facts, explicit preferences, system specs, "
                        "project credentials/configurations, or direct user instructions ('remember that...').\n\n"
                        "STRICT RULES:\n"
                        "1. IGNORE transient chat updates, status commentary, commands executed, temporary bug reports (e.g., 'they fixed it', 'duration was 5 mins', 'ran a terminal command', 'updated some things').\n"
                        "2. ONLY extract facts that remain true and useful for future sessions (e.g., 'User prefers dark mode', 'User's API port is 8080', 'User's preferred browser is Brave').\n"
                        "3. If no high-value, enduring facts are mentioned, return ONLY 'NO_FACTS'.\n"
                        "4. Output extracted facts as bullet points starting with '- '."
                    )
                ),
                Message(role="user", content=f"Text to evaluate:\n\n{content}"),
            ]
            
            from src.models.provider_router import ProviderRouter
            pr = ProviderRouter(self)
            dict_msgs = [{"role": m.role, "content": m.content} for m in messages]
            res = await pr.generate(dict_msgs, model_id=model_id, temperature=0.1, max_tokens=300)
            content_result = res.get("content", "").strip() if isinstance(res, dict) else ""
            
            if not content_result or content_result == "NO_FACTS" or "NO_FACTS" in content_result:
                return []
            
            facts = []
            for line in content_result.split("\n"):
                line = line.strip()
                if line.startswith("-") or line.startswith("*"):
                    facts.append(line.lstrip("-* "))
                elif line and not line.lower().startswith("here"):
                    facts.append(line)
            return facts
            
        except Exception as e:
            print(f"Error extracting memory facts: {e}")
            return []

    async def consolidate_memory_actions(
        self,
        existing_memories: List[Dict[str, Any]],
        new_facts: List[str],
        model_id: str = "openai/gpt-oss-120b",
    ) -> List[Dict[str, Any]]:
        """Compare new facts against existing memories to decide whether to ADD, UPDATE, or SKIP."""
        if not new_facts:
            return []
            
        if not existing_memories:
            return [{"action": "add", "content": fact} for fact in new_facts]
            
        try:
            memories_formatted = json.dumps([{"id": m["id"], "content": m["content"]} for m in existing_memories])
            facts_formatted = json.dumps(new_facts)
            
            messages = [
                Message(
                    role="system",
                    content=(
                        "You are an AI Memory Consolidation Engine.\n"
                        "Compare NEW_FACTS against EXISTING_MEMORIES.\n"
                        "For each new fact, output a JSON object with:\n"
                        "- {\"action\": \"update\", \"memory_id\": \"<existing_id>\", \"content\": \"<new_updated_fact>\"} if it updates/replaces an existing memory.\n"
                        "- {\"action\": \"skip\"} if it is already recorded.\n"
                        "- {\"action\": \"add\", \"content\": \"<fact>\"} if it is completely new.\n"
                        "Output ONLY a valid JSON list of action objects."
                    )
                ),
                Message(role="user", content=f"EXISTING_MEMORIES:\n{memories_formatted}\n\nNEW_FACTS:\n{facts_formatted}"),
            ]
            
            from src.models.provider_router import ProviderRouter
            pr = ProviderRouter(self)
            dict_msgs = [{"role": m.role, "content": m.content} for m in messages]
            res = await pr.generate(dict_msgs, model_id=model_id, temperature=0.1, max_tokens=500)
            raw_json = res.get("content", "").strip() if isinstance(res, dict) else ""

            if raw_json:
                if "```" in raw_json:
                    raw_json = raw_json.split("```")[1]
                    if raw_json.startswith("json"):
                        raw_json = raw_json[4:]
                raw_json = raw_json.strip()
                return json.loads(raw_json)
        except Exception as e:
            print(f"Memory consolidation fallback: {e}")
            
        return [{"action": "add", "content": fact} for fact in new_facts]

    async def extract_tags(
        self,
        content: str,
        model_id: Optional[str] = None,
        use_heuristic: bool = True,
    ) -> List[str]:
        """Extract tags from content using LLM or heuristic."""
        # If model is specified, use LLM
        if model_id:
            try:
                messages = [
                    Message(role="system", content="Extract 3-5 key topic tags from the content. Return only comma-separated tags, no explanations."),
                    Message(role="user", content=f"Extract tags from:\n\n{content}"),
                ]
                
                request = ChatRequest(
                    model=model_id,
                    messages=messages,
                    temperature=0.1,
                    max_tokens=100,
                    stream=False,
                )
                
                response = await self.client.post(
                    f"{self.base_url}/chat/completions",
                    json=request.dict(exclude_none=True),
                )
                response.raise_for_status()
                
                data = response.json()
                
                # Track cost
                if data.get("usage"):
                    usage = data["usage"]
                    input_tokens = usage.get("prompt_tokens", 0)
                    output_tokens = usage.get("completion_tokens", 0)
                    config.track_cost(model_id, input_tokens, output_tokens)
                
                # Parse tags
                if "choices" in data and data["choices"]:
                    choice = data["choices"][0]
                    if "message" in choice and "content" in choice["message"]:
                        tags_text = choice["message"]["content"].strip()
                        tags = [tag.strip() for tag in tags_text.split(",") if tag.strip()]
                        return tags
                
            except Exception as e:
                print(f"Error in tag extraction with LLM: {e}")
                # Fall back to heuristic if LLM fails
                if use_heuristic:
                    return self._heuristic_tags(content)
                return []
        
        # Use heuristic if no model or fallback
        if use_heuristic:
            return self._heuristic_tags(content)
        
        return []
    
    def _heuristic_tags(self, content: str) -> List[str]:
        """Extract tags using simple heuristics."""
        import re
        
        # Common stop words to filter out
        stop_words = {"the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for", "of", "with", "by", "is", "are", "was", "were", "be", "been", "being"}
        
        # Extract words (3+ letters) that appear multiple times
        words = re.findall(r'\b[a-zA-Z]{3,}\b', content.lower())
        word_counts = {}
        
        for word in words:
            if word not in stop_words:
                word_counts[word] = word_counts.get(word, 0) + 1
        
        # Get top 5 most frequent words as tags
        tags = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)[:5]
        return [tag[0] for tag in tags]


# Helper function to create message list
def create_messages(system_prompt: str, user_message: str) -> List[Message]:
    """Create message list from system prompt and user message."""
    return [
        Message(role="system", content=system_prompt),
        Message(role="user", content=user_message),
    ]